In [3]:
!pip install pandas 
!pip install numpy
!pip install sickit-learn
!pip install matplotlib

Requirement already satisfied: pandas in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (2.3.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from pandas) (2.3.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (2.3.1)

ERROR: Could not find a version that satisfies the requirement sickit-learn (from versions: none)
ERROR: No matching distribution found for sickit-learn

Requirement already satisfied: matplotlib in c:\users\user\appdata\roaming\python\python313\site-packages (3.10.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib) (4.58.4)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from matplotlib) (2.3.1)
Requirement already satisfied: packaging>=20.0 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\user\appdata\roaming\python\python313\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\user\anaconda3\envs\ml_env_log_reg\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

In [43]:
import pandas as pd 
import matplotlib.pyplot as plt 
import numpy as np 
import sklearn

In [44]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv"
df=pd.read_csv(url)

In [45]:
df.head()

,tenure,age,address,income,ed,employ,equip,callcard,wireless,longmon,...,pager,internet,callwait,confer,ebill,loglong,logtoll,lninc,custcat,churn
0,11.0,33.0,7.0,136.0,5.0,5.0,0.0,1.0,1.0,4.40,...,1.0,0.0,1.0,1.0,0.0,1.482,3.033,4.913,4.0,1.0
1,33.0,33.0,12.0,33.0,2.0,0.0,0.0,0.0,0.0,9.45,...,0.0,0.0,0.0,0.0,0.0,2.246,3.240,3.497,1.0,1.0
2,23.0,30.0,9.0,30.0,1.0,2.0,0.0,0.0,0.0,6.30,...,0.0,0.0,0.0,1.0,0.0,1.841,3.240,3.401,3.0,0.0
3,38.0,35.0,5.0,76.0,2.0,10.0,1.0,1.0,1.0,6.05,...,1.0,1.0,1.0,1.0,1.0,1.800,3.807,4.331,4.0,0.0
4,7.0,35.0,14.0,80.0,2.0,15.0,0.0,1.0,0.0,7.10,...,0.0,0.0,1.0,1.0,0.0,1.960,3.091,4.382,3.0,0.0

In [46]:
cdf_churn =df[["tenure","age","address","income","ed","employ","churn"]]
cdf_churn["churn"]=cdf_churn["churn"].astype('int')
cdf_churn

C:\Users\user\AppData\Local\Temp\ipykernel_22668\646345712.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cdf_churn["churn"]=cdf_churn["churn"].astype('int')

     tenure   age  address  income   ed  employ  churn
0      11.0  33.0      7.0   136.0  5.0     5.0      1
1      33.0  33.0     12.0    33.0  2.0     0.0      1
2      23.0  30.0      9.0    30.0  1.0     2.0      0
3      38.0  35.0      5.0    76.0  2.0    10.0      0
4       7.0  35.0     14.0    80.0  2.0    15.0      0
..      ...   ...      ...     ...  ...     ...    ...
195    55.0  44.0     24.0    83.0  1.0    23.0      0
196    34.0  23.0      3.0    24.0  1.0     7.0      0
197     6.0  32.0     10.0    47.0  1.0    10.0      0
198    24.0  30.0      0.0    25.0  4.0     5.0      1
199    61.0  50.0     16.0   190.0  2.0    22.0      0

[200 rows x 7 columns]

In [47]:
X=np.asarray(cdf_churn[["tenure","age","address","income","ed","employ"]])
y=np.asarray(cdf_churn["churn"])

In [48]:
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.],
       [ 33.,  33.,  12.,  33.,   2.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.],
       [ 38.,  35.,   5.,  76.,   2.,  10.],
       [  7.,  35.,  14.,  80.,   2.,  15.]])

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import log_loss
from sklearn.model_selection import train_test_split

In [50]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [51]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)  # utiliser le mÃªme scaler

In [52]:
LR=LogisticRegression().fit(X_train_scaled, y_train)

In [53]:
y_pred=LR.predict(X_test_scaled)
y_pred

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1])

In [54]:
y_pred_prob=LR.predict_proba(X_test_scaled)
y_pred_prob

array([[9.74877094e-01, 2.51229058e-02],
       [9.75270425e-01, 2.47295751e-02],
       [8.56107055e-01, 1.43892945e-01],
       [9.71861077e-01, 2.81389225e-02],
       [9.64366774e-01, 3.56332259e-02],
       [9.78086150e-01, 2.19138498e-02],
       [4.11301088e-01, 5.88698912e-01],
       [3.91261814e-01, 6.08738186e-01],
       [9.99182494e-01, 8.17506000e-04],
       [6.60856225e-01, 3.39143775e-01],
       [4.27612386e-01, 5.72387614e-01],
       [9.66193862e-01, 3.38061385e-02],
       [6.28008746e-01, 3.71991254e-01],
       [5.84795014e-01, 4.15204986e-01],
       [9.38786019e-01, 6.12139810e-02],
       [9.79496990e-01, 2.05030105e-02],
       [8.48632879e-01, 1.51367121e-01],
       [9.21403531e-01, 7.85964693e-02],
       [6.90893288e-01, 3.09106712e-01],
       [8.07095129e-01, 1.92904871e-01],
       [9.52806226e-01, 4.71937740e-02],
       [4.59331855e-01, 5.40668145e-01],
       [7.90964692e-01, 2.09035308e-01],
       [5.05266965e-01, 4.94733035e-01],
       [8.96329111e-01, 1.03670889e-01],
       [8.41562643e-01, 1.58437357e-01],
       [8.95545735e-01, 1.04454265e-01],
       [9.84090299e-01, 1.59097011e-02],
       [6.42232126e-01, 3.57767874e-01],
       [4.97417282e-01, 5.02582718e-01],
       [9.75275911e-01, 2.47240892e-02],
       [8.32096023e-01, 1.67903977e-01],
       [9.10383130e-01, 8.96168697e-02],
       [9.10986811e-01, 8.90131890e-02],
       [9.50167628e-01, 4.98323721e-02],
       [3.78495040e-01, 6.21504960e-01],
       [6.67164266e-01, 3.32835734e-01],
       [4.40281404e-01, 5.59718596e-01],
       [7.38493429e-01, 2.61506571e-01],
       [4.45817659e-01, 5.54182341e-01]])

In [55]:
from sklearn.metrics import log_loss
log_loss=log_loss(y_test,y_pred)

In [57]:
with open("modele_churn1.pkl", "wb") as f:
    pickle.dump(LR, f)

with open("scaler.pkl", "wb") as f:
    pickle.dump(scaler, f)

In [42]:
print(cdf_churn['churn'].value_counts())

churn
0    142
1     58
Name: count, dtype: int64

In [60]:
# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
import pickle
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss, accuracy_score, classification_report, roc_auc_score

# Charger ton dataset
# df = pd.read_csv("ton_dataset.csv")  # dÃ©commente si CSV
cdf_churn = df[["tenure", "age", "address", "income", "ed", "employ", "churn"]].copy()
cdf_churn["churn"] = cdf_churn["churn"].astype(int)

# SÃ©parer X et y
X = np.asarray(cdf_churn[["tenure", "age", "address", "income", "ed", "employ"]])
y = np.asarray(cdf_churn["churn"])

# Split train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# Standardisation
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# EntraÃ®ner le modÃ¨le avec gestion du dÃ©sÃ©quilibre
LR = LogisticRegression(class_weight='balanced', random_state=42)
LR.fit(X_train_scaled, y_train)

# PrÃ©dictions
y_pred = LR.predict(X_test_scaled)
y_pred_prob = LR.predict_proba(X_test_scaled)[:,1]

# Ã‰valuation
acc = accuracy_score(y_test, y_pred)
loss = log_loss(y_test, y_pred_prob)
roc_auc = roc_auc_score(y_test, y_pred_prob)
print(f"Accuracy: {acc:.3f}")
print(f"Log Loss: {loss:.3f}")
print(f"ROC-AUC: {roc_auc:.3f}")
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# Sauvegarder le modÃ¨le et le scaler
with open("modele_churn_balanced.pkl", "wb") as f:
    pickle.dump(LR, f)

with open("scaler_balanced.pkl", "wb") as f:
    pickle.dump(scaler, f)

Accuracy: 0.725
Log Loss: 0.575
ROC-AUC: 0.729

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.75      0.79        28
           1       0.53      0.67      0.59        12

    accuracy                           0.72        40
   macro avg       0.69      0.71      0.69        40
weighted avg       0.75      0.72      0.73        40